Repository IBM/ibm-spectrum-scale-install-infra, pull requests merged in 2020-12, with the labels that each got.

#301 Documentation updates
  README.md
  VARIABLES.md
Labels: Component: Documentation, Type: Documentation, Type: Enhancement

#315 New role for remote mounted filesystem
  roles/remote_mount/.yamllint
  roles/remote_mount/README.md
  roles/remote_mount/defaults/main.yml
  roles/remote_mount/handlers/main.yml
  roles/remote_mount/meta/main.yml
  roles/remote_mount/molecule/default/INSTALL.rst
  roles/remote_mount/molecule/default/converge.yml
  roles/remote_mount/molecule/default/molecule.yml
  roles/remote_mount/molecule/default/verify.yml
  roles/remote_mount/tasks/cleanup_filesystem.yml
  roles/remote_mount/tasks/cleanup_remote_mount.yml
  roles/remote_mount/tasks/delete_remote_cluster.yml
  roles/remote_mount/tasks/main.yml
  roles/remote_mount/tasks/mount_filesystem.yml
  roles/remote_mount/tasks/mount_filesystem_api_cli.yml
  roles/remote_mount/tasks/precheck.yml
  roles/remote_mount/tests/inventory
  roles/remote_mount/tests/test.yml
  roles/remote_mount/vars/main.yml
  samples/playbook_remote_mount.yml
Labels: Type: Enhancement

#325 Scale storage decouple NSD's and filesystem definition and creation
  roles/core/cluster/tasks/main.yml
  roles/core/cluster/tasks/storage_disk.yml
  roles/core/cluster/tasks/storage_fs.yml
  roles/core/cluster/templates/StanzaFile_fs.j2
  roles/core/cluster/templates/StanzaFile_nsd.j2
Labels: Component: Core, Severity: 2, Type: Enhancement

#332 Added flag node role change
  roles/core/cluster/defaults/main.yml
  roles/core/cluster/tasks/cluster_start.yml
  roles/scale_fileauditlogging/cluster/tasks/configure.yml
Labels: Severity: 3
